---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
data("instacart")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Plot A: Distribution of the Hour of the Day that Items in Each Department is Ordered

```{r}

instacart |>
  mutate(department = fct_reorder(department, order_hour_of_day)) |> 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box", colors = "viridis") |>
  layout(
    xaxis = list(title = "Department"),
    yaxis = list(title = "Hour of the Day Ordered"),
    legend = list(title = list(text = "Department"))
  )


```

Column {data-width=500}
-----------------------------------------------------------------------

### Plot B: Bar Graph Displaying Number of Times Ordered for Each Department

```{r}
instacart |>
  group_by(department) |>
  summarize(count = n()) |>
  mutate(department = fct_reorder(department, count)) |>
  plot_ly(x = ~department, y = ~count, 
          color = ~department, type = "bar", colors = "viridis") |>
  layout(
    xaxis = list(title = "Department"),
    yaxis = list(title = "Number of Times Ordered"),
    legend = list(title = list(text = "Department"))
  )


```

### Plot C: Histogram Displaying Number of Times Each Aisle within Every Department is Ordered

```{r}

instacart |>
  group_by(department, aisle) |>
  mutate(aisle = fct_reorder(aisle, department)) |>
  plot_ly(
    x = ~aisle, color = ~department, type = "histogram") |>
  layout(
    xaxis = list(title = "Aisle"),
    yaxis = list(title = "Number of Times Ordered"),
    legend = list(title = list(text = "Department"))
  )

```

